// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: dynamic.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseDynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID int64 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
}

func (x *BaseDynamicRequest) Reset() {
	*x = BaseDynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseDynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseDynamicRequest) ProtoMessage() {}

func (x *BaseDynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseDynamicRequest.ProtoReflect.Descriptor instead.
func (*BaseDynamicRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *BaseDynamicRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type DynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseCommentRequest *BaseDynamicRequest `protobuf:"bytes,1,opt,name=baseCommentRequest,proto3" json:"baseCommentRequest,omitempty"`
	Offect             int64               `protobuf:"varint,2,opt,name=Offect,proto3" json:"Offect,omitempty"`
}

func (x *DynamicRequest) Reset() {
	*x = DynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRequest) ProtoMessage() {}

func (x *DynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRequest.ProtoReflect.Descriptor instead.
func (*DynamicRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicRequest) GetBaseCommentRequest() *BaseDynamicRequest {
	if x != nil {
		return x.BaseCommentRequest
	}
	return nil
}

func (x *DynamicRequest) GetOffect() int64 {
	if x != nil {
		return x.Offect
	}
	return 0
}

type AllDynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseCommentRequest *BaseDynamicRequest `protobuf:"bytes,1,opt,name=baseCommentRequest,proto3" json:"baseCommentRequest,omitempty"`
	Time               int64               `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *AllDynamicRequest) Reset() {
	*x = AllDynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllDynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllDynamicRequest) ProtoMessage() {}

func (x *AllDynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllDynamicRequest.ProtoReflect.Descriptor instead.
func (*AllDynamicRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{2}
}

func (x *AllDynamicRequest) GetBaseCommentRequest() *BaseDynamicRequest {
	if x != nil {
		return x.BaseCommentRequest
	}
	return nil
}

func (x *AllDynamicRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type DynamicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID     int64  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Card    string `protobuf:"bytes,3,opt,name=Card,proto3" json:"Card,omitempty"`
	RID     int64  `protobuf:"varint,4,opt,name=RID,proto3" json:"RID,omitempty"`
	Offect  int64  `protobuf:"varint,5,opt,name=Offect,proto3" json:"Offect,omitempty"`
	Type    int32  `protobuf:"varint,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Name    string `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Time    int64  `protobuf:"varint,8,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *DynamicResponse) Reset() {
	*x = DynamicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicResponse) ProtoMessage() {}

func (x *DynamicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicResponse.ProtoReflect.Descriptor instead.
func (*DynamicResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{3}
}

func (x *DynamicResponse) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *DynamicResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DynamicResponse) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *DynamicResponse) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *DynamicResponse) GetOffect() int64 {
	if x != nil {
		return x.Offect
	}
	return 0
}

func (x *DynamicResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DynamicResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DynamicResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_dynamic_proto protoreflect.FileDescriptor

var file_dynamic_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x26, 0x0a, 0x12, 0x42, 0x61, 0x73, 0x65, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x22, 0x72, 0x0a,
	0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x12, 0x62, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x22, 0x71, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x12, 0x62, 0x61,
	0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x7f,
	0x0a, 0x07, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x3c, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamic_proto_rawDescOnce sync.Once
	file_dynamic_proto_rawDescData = file_dynamic_proto_rawDesc
)

func file_dynamic_proto_rawDescGZIP() []byte {
	file_dynamic_proto_rawDescOnce.Do(func() {
		file_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_proto_rawDescData)
	})
	return file_dynamic_proto_rawDescData
}

var file_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dynamic_proto_goTypes = []interface{}{
	(*BaseDynamicRequest)(nil), // 0: grpc.BaseDynamicRequest
	(*DynamicRequest)(nil),     // 1: grpc.DynamicRequest
	(*AllDynamicRequest)(nil),  // 2: grpc.AllDynamicRequest
	(*DynamicResponse)(nil),    // 3: grpc.DynamicResponse
}
var file_dynamic_proto_depIdxs = []int32{
	0, // 0: grpc.DynamicRequest.baseCommentRequest:type_name -> grpc.BaseDynamicRequest
	0, // 1: grpc.AllDynamicRequest.baseCommentRequest:type_name -> grpc.BaseDynamicRequest
	1, // 2: grpc.Dynamic.Get:input_type -> grpc.DynamicRequest
	2, // 3: grpc.Dynamic.GetAll:input_type -> grpc.AllDynamicRequest
	3, // 4: grpc.Dynamic.Get:output_type -> grpc.DynamicResponse
	3, // 5: grpc.Dynamic.GetAll:output_type -> grpc.DynamicResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dynamic_proto_init() }
func file_dynamic_proto_init() {
	if File_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseDynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllDynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamic_proto_goTypes,
		DependencyIndexes: file_dynamic_proto_depIdxs,
		MessageInfos:      file_dynamic_proto_msgTypes,
	}.Build()
	File_dynamic_proto = out.File
	file_dynamic_proto_rawDesc = nil
	file_dynamic_proto_goTypes = nil
	file_dynamic_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DynamicClient is the client API for Dynamic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DynamicClient interface {
	Get(ctx context.Context, in *DynamicRequest, opts ...grpc.CallOption) (Dynamic_GetClient, error)
	GetAll(ctx context.Context, in *AllDynamicRequest, opts ...grpc.CallOption) (Dynamic_GetAllClient, error)
}

type dynamicClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicClient(cc grpc.ClientConnInterface) DynamicClient {
	return &dynamicClient{cc}
}

func (c *dynamicClient) Get(ctx context.Context, in *DynamicRequest, opts ...grpc.CallOption) (Dynamic_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dynamic_serviceDesc.Streams[0], "/grpc.Dynamic/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &dynamicGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Dynamic_GetClient interface {
	Recv() (*DynamicResponse, error)
	grpc.ClientStream
}

type dynamicGetClient struct {
	grpc.ClientStream
}

func (x *dynamicGetClient) Recv() (*DynamicResponse, error) {
	m := new(DynamicResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dynamicClient) GetAll(ctx context.Context, in *AllDynamicRequest, opts ...grpc.CallOption) (Dynamic_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dynamic_serviceDesc.Streams[1], "/grpc.Dynamic/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &dynamicGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Dynamic_GetAllClient interface {
	Recv() (*DynamicResponse, error)
	grpc.ClientStream
}

type dynamicGetAllClient struct {
	grpc.ClientStream
}

func (x *dynamicGetAllClient) Recv() (*DynamicResponse, error) {
	m := new(DynamicResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DynamicServer is the server API for Dynamic service.
type DynamicServer interface {
	Get(*DynamicRequest, Dynamic_GetServer) error
	GetAll(*AllDynamicRequest, Dynamic_GetAllServer) error
}

// UnimplementedDynamicServer can be embedded to have forward compatible implementations.
type UnimplementedDynamicServer struct {
}

func (*UnimplementedDynamicServer) Get(*DynamicRequest, Dynamic_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDynamicServer) GetAll(*AllDynamicRequest, Dynamic_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterDynamicServer(s *grpc.Server, srv DynamicServer) {
	s.RegisterService(&_Dynamic_serviceDesc, srv)
}

func _Dynamic_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DynamicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DynamicServer).Get(m, &dynamicGetServer{stream})
}

type Dynamic_GetServer interface {
	Send(*DynamicResponse) error
	grpc.ServerStream
}

type dynamicGetServer struct {
	grpc.ServerStream
}

func (x *dynamicGetServer) Send(m *DynamicResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Dynamic_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllDynamicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DynamicServer).GetAll(m, &dynamicGetAllServer{stream})
}

type Dynamic_GetAllServer interface {
	Send(*DynamicResponse) error
	grpc.ServerStream
}

type dynamicGetAllServer struct {
	grpc.ServerStream
}

func (x *dynamicGetAllServer) Send(m *DynamicResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Dynamic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Dynamic",
	HandlerType: (*DynamicServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Dynamic_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _Dynamic_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dynamic.proto",
}
